apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service-app
  # namespace: jenkins
  labels:
    app: quiz-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service-app
  template:
    metadata:
      labels:
        app: quiz-service-app
    spec:
      containers:
        - name: quiz-service-app
          image: saihemanth1997/quiz-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: EUREKA_HOSTNAME
            - name: EUREKA_REGISTER_WITH_EUREKA
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: EUREKA_REGISTER_WITH_EUREKA
            - name: EUREKA_FETCH_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: EUREKA_FETCH_REGISTRY
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: EUREKA_DEFAULT_ZONE
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: quiz-service-config
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "512Mi"   # Adjust memory request
              cpu: "500m"       # Adjust CPU request
            limits:
              memory: "1Gi"   # Adjust memory limit
              cpu: "1"           
        
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service-app
  # namespace: jenkins
spec:
  # type: NodePort
  selector:
    app: quiz-service-app
  ports:
    - port: 80
      targetPort: 8090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-service-config
  # namespace: jenkins
data:
  EUREKA_HOSTNAME: eureka-0
  EUREKA_REGISTER_WITH_EUREKA: "true"
  EUREKA_FETCH_REGISTRY: "true"
  EUREKA_DEFAULT_ZONE: http://eureka-0.eureka.webapps.svc.cluster.local:8761/eureka
  DB_URL: jdbc:mysql://mysql-svc:3306/Quiz?createDatabaseIfNotExist=true
  DB_USERNAME: root
  DB_PASSWORD: Hemanth@2000
