# documentation.

name: Microservices CI/CD Pipeline
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          distribution: "temurin"
          cache: maven

      - name: Building and Pushing Question Service
        run: mvn  package dockerfile:push --file question-service/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Quiz Service
        run: mvn  package dockerfile:push --file quiz-service/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Contribute Service
        run: mvn  package dockerfile:push --file contribute-service/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Config server
        run: mvn  package dockerfile:push --file cloud-config-server/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Server registry
        run: mvn  package dockerfile:push --file service-registry/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Api gateway
        run: mvn  package dockerfile:push --file api-gateway/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Microservices to Local Kubernetes Cluster
        run: |
          kubectl apply -f k8s/
